apiVersion: v1
kind: Service
metadata:
  name: {{ include "container-scan-app.fullname" . }}-nginx
  labels:
    app: {{ include "container-scan-app.name" . }}
    component: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: {{ include "container-scan-app.name" . }}
    component: nginx
