apiVersion: v1
kind: Service
metadata:
  name: {{ include "container-scan-app.fullname" . }}-node
  labels:
    app: {{ include "container-scan-app.name" . }}
    component: node
spec:
  ports:
    - port: {{ .Values.node.service.port }}
      targetPort: {{ .Values.node.service.port }}
  selector:
    app: {{ include "container-scan-app.name" . }}
    component: node
