apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "container-scan-app.fullname" . }}-nginx-config
  labels:
    app: {{ include "container-scan-app.name" . }}
    component: nginx
data:
  default.conf: |-
    server {
        listen 80;

        location / {
            proxy_pass http://{{ include "container-scan-app.fullname" . }}-node:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }