apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "container-scan-app.fullname" . }}-postgres
  labels:
    app: {{ include "container-scan-app.name" . }}
    tier: backend
    component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "container-scan-app.name" . }}
      component: postgres
  template:
    metadata:
      labels:
        app: {{ include "container-scan-app.name" . }}
        component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.env.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.env.POSTGRES_PASSWORD }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.env.POSTGRES_DB }}"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "container-scan-app.fullname" . }}-postgres-pvc
